services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    container_name: rouvia-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    container_name: rouvia-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped